FROM python:3.8.5

COPY requirements.txt .

RUN apt-get update
RUN pip3 install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install PyMySQL
RUN pip install flasgger
RUN pip install cryptography

WORKDIR /app

COPY . /app

EXPOSE 5000

ENTRYPOINT ["python3"]

CMD ["app.py"]