version: '3'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile-server
    networks:
      - default
      - net_backend
    ports:
      - "5040:5040"
    container_name: server


  mysql:
    image: mysql
    restart: always
    container_name: db
    ports:
      - "3306:3306"
    env_file:
      - ./envs/mysqlenv
    volumes:
      - ./envs/mysql-init-files/:/docker-entrypoint-initdb.d/
      #- ./db/data:/var/lib/mysql
    #environment:
      #TZ: Asia/Seoul
      #MYSQL_ROOT_PASSWORD: admin
      #MYSQL_DATABASE: project1
    networks:
      - default
      - net_backend


networks:
  net_backend:
    driver: bridge