version: '3'

services:
  back-end:
    build: .
    networks:
      - default
      - project1_backend

  mysql_db:
    image: mysql
    restart: always
    container_name: project1_db
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: project1
    networks:
      - default
      - project1_backend


networks:
  project1_backend:
    driver: bridge