version: '3'

services:
  db:
    image: mysql
    restart: always
    container_name: project1_db
    ports:
      - "3306:3306"
    #env_file:
    #  - ./envs/mysqlenv # mysql environment set
    #volumes:
      #- ./envs/mysql-init-files/:/docker-entrypoint-initdb.d/ # mysql init
      #- ./db/data:/var/lib/mysql # save to host mysql data 
    environment:
      - TZ=Asia/Seoul
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=project1
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - default
      - p1_net


  api:
    depends_on:
      - db
    restart: always    
    build: 
      context: .  # path
    # dockerfile: Dockerfile-server # flask build
    networks:
      - default
      - p1_net
    ports:
      - "5040:5040"
    environment:
      - FLASK_APP=./src/app.py
    container_name: project1_api


networks:
  p1_net:
    driver: bridge