version: '3'

services:
  back-end:
    build: 
      context: ../dockerfiles
      dockerfile: Dockerfile-server
    networks:
      - default
      - project1_backend
    ports:
      - "5040:5040"
    container_name: project1_back


  mysql_db:
    image: mysql
    restart: always
    container_name: project1_db
    ports:
      - "3306:3306"
    #volumes:
      #- ./db/data:/var/lib/mysql
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: project1
    networks:
      - default
      - project1_backend


networks:
  project1_backend:
    driver: bridge