use project1;

CREATE TABLE tb_task (
    id INT AUTO_INCREMENT,
    todo VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
)ENGINE=INNODB;

/*CREATE DATABASE IF NOT EXISTS project1 default CHARACTER SET UTF8;*/