name: api ci

on:
  push:
    branches:
      - develop
      
jobs:
  docker:
    name: Docker Compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU For Docker
        uses: docker/setup-qemu-action@v1
        
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          script: "docker-compose pull && docker-compose up -d && docker-compose up --force-recreate --build -d && docker image prune -f"
        
      
