# This is a basic workflow to help you get started with Actions

name: buld N push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # image update
      - name: docker image pull
        run: docker-compose.yml pull
        
      # docker build
      - name: docker recreate
        run: docker-compose.yml up --force-recreate --build -d
        
      # prev image delete
      - name: image clean up
        run: docker image prune -f
